{% set name = "mpi_serial" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MCSclimate/mpi-serial/archive/refs/tags/MPIserial_{{ version }}.tar.gz
  sha256: 2faf459ea1f37020662067e7ab6c76b926501c4b94e8fdf77591c0040ba1f006

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('mpi_serial', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - coreutils  # [unix]
    - make  # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool   # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - m2-autoconf  # [win]
    - m2-automake-wrapper  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-libtool  # [win]
    - m2-m4  # [win]
    - m2-make  # [win]
    - m2-sed  # [win]
    # - m2-which  # [win]
    # - m2w64-pkg-config  # [win]
    # - m2w64-dlfcn  # [win]
  host:
  run:
    - mpi 1.0 mpi_serial

test:
  commands:
    - test -f $PREFIX/lib/libmpi-serial.a
    - test -f $PREFIX/include/mpi.h
    - test -f $PREFIX/include/mpif.h

about:
  home: https://github.com/MCSclimate/mpi-serial
  summary: MPI library for single processor
  description: |
    This library provides a one-processor version of MPI.  Most common MPI calls,
    including all that are necessary for the Model Coupling Toolkit, are supported.
    This includes sends and receives (which cannot be simply stubbed out).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/MCSclimate/mpi-serial
  dev_url: https://github.com/MCSclimate/mpi-serial

extra:
  recipe-maintainers:
    - zklaus
    - mahf708
    - xylar
